# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: terraform 
  pool: Default
  jobs:
  - job: codes
    steps:
     - task: TerraformTaskV4@4
       inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/Terraform/Azure/kubernetesCluster'
        backendServiceArm: 'ms3'
        backendAzureRmResourceGroupName: 'nt-poc-akshaya'
        backendAzureRmStorageAccountName: 'sinkstrgadf'
        backendAzureRmContainerName: 'sink'
        backendAzureRmKey: 'rg/terraform.tfstate'
        
     - task: TerraformTaskV4@4
       inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)/Terraform/Azure/kubernetesCluster'
        environmentServiceNameAzureRM: 'ms3'

