# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line scrip t'

- script: |
    az login --service-principal -u 86076dbf-debc-44ba-b4f5-c90686150665 -p nh08Q~qnTpwwFOkQMp1klMK_dFHUVwVTWmF1pbtS --tenant 00bb5983-b28f-4542-a099-20eaf8bbb209


- task: TerraformCLI@0
  inputs:
    command: 'init'
    allowTelemetryCollection: true

- task: TerraformCLI@0
  inputs:
    command: 'apply'
    allowTelemetryCollection: true

