# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line scrip t'

- task: AzureCLI@2
  displayName: Azure CLI
  inputs:
    azureSubscription: ms3
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az --version
      az account show
   

- task: TerraformCLI@0
  inputs:
    command: 'init'
    allowTelemetryCollection: true

- task: TerraformCLI@0
  inputs:
    command: 'apply'
    allowTelemetryCollection: true

