# stages:
#   - stage: login
#     pool: Default
#     jobs:  
#       - job: check_env_var
#         # dependsOn: clean_folder
#         steps:
#           - task: PowerShell@2
#           - script: echo Hello, world!
#             displayName: 'Run a one-line script'
           
#       - job: stage_login
#         dependsOn: check_env_var- script: echo Hello, world!
#               scriptType: bash
#               scriptLocation: inlineScript
#               inlineScript: |
#                 az --version
#                 az account show
trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
  - job: check_env
    steps:
      - task: PowerShell@2
      - script: echo Hello, world!
  
  - job: stage_login
    dependsOn: check_env
    steps:
    
    - task: AzureCLI@2
      displayName: Azure CLI
      inputs:
        azureSubscription: ms3
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az --version
          az account show
    
